### ISSUE TITLE
Missing front view

### ISSUE THREAD

**Issue by airtonix** [jessepollak/card#15]
Missing some critical toggle styles: 
![screenshot from 2014-06-05 09 49 57](https://cloud.githubusercontent.com/assets/61225/3181933/66e2962a-ec47-11e3-8f42-7f7ada6b3a37.png)

using: Google Chrome Version 34.0.1847.132
Work as expected After adding the following in chrome devtools: 

```css
div.card .front {
  display: block;
}
div.card .back {
  display: none;
}

div.card.flipped .front {
  display: none;
}
div.card.flipped .back {
  display: block;
}
```
