### ISSUE TITLE
.card-logo css class duplicated for every card type

### ISSUE THREAD

**Issue by icanhasjonas** [jessepollak/card#88]
Code duplicated for each card type:

``` CSS
.card-logo {
  height: 36px;
  width: 60px;
  font-style: italic; }
  .card-logo, .card-logo:before, .card-logo:after {
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box; }
```
